version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
