version: '3.7'

services:
  web:
    build: ./services/web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cmuser
      - POSTGRES_PASSWORD=cm
      - POSTGRES_DB=cm

  scrapyd:
    build: ./services/scrapyd
    image: scrapyd
    ports:
      - 6800:6800
    environment:
      - POSTGRES_URL=postgresql://cmuser:cm@db:5432/cm
    depends_on:
      - db
    restart: always

volumes:
  postgres_data:
