version: '3.7'

services:
  dev-web:
    build: ./services/web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - dev-db
      - redis
      - chromedriver

  dev-db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=cmuser
      - POSTGRES_PASSWORD=cm
      - POSTGRES_DB=cm

  redis:
    image: redis:6.0-alpine
    ports:
      - 6379:6379

  celery:
    build:
      context: ./services/web
      dockerfile: "Dockerfile.celery"
    command: celery -A config worker -B -l INFO
    env_file:
      - ./.env.dev
    depends_on:
      - dev-db
      - redis

  dev-scrapyd:
    build: ./services/scrapyd
    image: scrapyd
    ports:
      - 6800:6800
    environment:
      - POSTGRES_URL=postgresql://cmuser:cm@dev-db:5432/cm
    depends_on:
      - dev-db
    restart: always

  chromedriver:
    image: chromedriver
    build: ./services/chromedriver
    init: true
    command:
      - chromedriver
      - --whitelisted-ips
    volumes:
      - /dev/shm:/dev/shm

volumes:
  postgres_data:
