# Generated by Django 3.1 on 2020-09-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_auto_20200831_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='extra_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_top', to='closet.clothes', verbose_name='extra top'),
        ),
    ]
