# Generated by Django 3.1 on 2020-09-01 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_auto_20200901_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='outerwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outerwear', to='closet.clothes', verbose_name='outerwear'),
        ),
    ]
