# Generated by Django 3.1 on 2020-08-29 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200825_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='_user_followers_+', through='accounts.FollowUser', to=settings.AUTH_USER_MODEL, verbose_name='followers'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, related_name='_user_followings_+', through='accounts.FollowUser', to=settings.AUTH_USER_MODEL, verbose_name='following users'),
        ),
    ]
