# Generated by Django 3.1 on 2020-08-31 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='publish',
            field=models.BooleanField(default=False, verbose_name='publish'),
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('publish', models.BooleanField(default=False, verbose_name='publish')),
                ('bottom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottom', to='closet.clothes', verbose_name='bottom')),
                ('extra_top', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='extra_top', to='closet.clothes', verbose_name='extra top')),
                ('outerwear', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outerwear', to='closet.clothes', verbose_name='outerwear')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='top', to='closet.clothes', verbose_name='top')),
            ],
        ),
    ]
