# Generated by Django 3.1.2 on 2020-10-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='clothes_pic/'),
        ),
    ]
