# Generated by Django 3.1.2 on 2020-10-29 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='second_weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='second', to='closet.weatherelement'),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='weather_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change', to='closet.weatherelement'),
        ),
    ]
