# Generated by Django 3.1.2 on 2020-10-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_auto_20201006_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='color'),
        ),
    ]
