# Generated by Django 3.1.2 on 2020-10-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0003_auto_20201012_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='original',
            field=models.CharField(max_length=64, null=True, verbose_name='original'),
        ),
    ]
