# Generated by Django 3.1.1 on 2020-09-15 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0004_auto_20200901_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='area')),
            ],
        ),
        migrations.CreateModel(
            name='ClothesIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(verbose_name='value')),
                ('description', models.TextField(blank=True, verbose_name='description')),
            ],
        ),
        migrations.AddField(
            model_name='clothes',
            name='picture',
            field=models.ImageField(blank=True, upload_to='clothes_pic/'),
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='prefecture')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='closet.area', verbose_name='area')),
            ],
        ),
        migrations.CreateModel(
            name='IndexCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditional', models.BooleanField(default=False, verbose_name='conditional')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.category')),
                ('clothes_index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='closet.clothesindex')),
            ],
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather', models.CharField(max_length=255, verbose_name='weather')),
                ('highest_temp', models.IntegerField(verbose_name='highest tempreture')),
                ('lowest_temp', models.IntegerField(verbose_name='lowest tempreture')),
                ('rain_chance', models.IntegerField(verbose_name='rain chance')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast', to='closet.area', verbose_name='area')),
                ('clothes_index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast', to='closet.clothesindex', verbose_name='clothes index')),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast', to='closet.prefecture', verbose_name='prefecture')),
            ],
        ),
        migrations.AddField(
            model_name='clothesindex',
            name='categories',
            field=models.ManyToManyField(through='closet.IndexCategory', to='closet.Category'),
        ),
    ]
